export type Pokemon = {
  aid: string;
  abilities: any[];
  forms: any[];
  game_indices: any[];
  base_experience?: number;
  height?: number;
  held_items?: any[];
  id: number;
  is_default?: boolean;
  location_area_encounters?: string;
  moves?: any[];
  name: string;
  order?: number;
  species?: any;
  type: any[];
  nickname?: string;
  weight?: number;
  past_types?: any[];
  sprites?: any;
};
